### ISSUE TITLE
Babel category

### ISSUE THREAD

**Issue by Banou26** [Z8264/frontend-developer-roadmap#2]
In the first image, there's Babel at some point, and you made a typo, it says `Complers` instead of `Compilers`.
I was also thinking about maybe replacing `Compilers` with `Transpilers` as it'd describe more specifically what is Babel.
And now Babel doesn't only do transpilations, they also provide polyfills with `core-js`, so it could even be `Transpilers / Polyfills` which would allow us to mention polyfills, which are quite big in the webdev industry.

**Comment by Z8264** [comment]
@Banou26 Thank you very much for your correction. I decided to fix it as you suggested.
